language: node_js

node_js:
    - 'node'
    - '10'
    - '8'

sudo: false

git:
    submodules: false

before_script:
    - wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
    - mkdir geckodriver
    - tar -xzf geckodriver-v0.24.0-linux64.tar.gz -C geckodriver
    - export PATH=$PATH:$PWD/geckodriver
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
